name: AntiScanner CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  antiscanner:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: Install AntiScanner CLI
        run: |
          curl -sSLo antiscanner.zip https://example.com/antiscanner-cli-latest.zip
          unzip antiscanner.zip -d $HOME/antiscanner
          export PATH="$HOME/antiscanner/bin:$PATH"

      - name: Run Static Code Analysis
        run: antiscanner static --project-key my_project_key --source-path src/ --language java,python,js

      - name: Run Dynamic Analysis
        run: antiscanner dynamic --url http://localhost:8080 --fuzz --auth-type oauth2

      - name: Run Dependency Scanning
        run: antiscanner depscan --project-key my_project_key --check-licenses --real-time-db true

      - name: Run Configuration Scanning
        run: antiscanner configscan --config-path config/ --iac terraform

      - name: Run Container Security Scan
        run: antiscanner containerscan --image myapp:latest

      - name: Run Kubernetes Security Scan
        run: antiscanner k8sscan --config-path k8s/

      - name: Generate Security Report
        run: antiscanner report --format html --output-path reports/ --integrate-grafana true

      - name: Upload Security Report
        uses: actions/upload-artifact@v2
        with:
          name: Security Report
          path: reports/
